name: Publish Package

on:
  release:
    types: [released]

env:
  # Versions are also listed in PR.yml
  POETRY_VERSION: 1.8.2
  PYTHON_VERSION: 3.11 # Use latest

jobs:
  publish_package:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }} # This is the branch the release was created from. Normally main, but can be a dev branch

      - name: Configure Git
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --tags -f

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Check for lock changes
        run: |
          poetry lock --check
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install the Package
        run: poetry install
      - name: Lint the Code
        run: poetry run ni-python-styleguide lint

      - name: Run tests
        run: poetry run pytest -v

      # If the version is 0.1.0-alpha.0, this will set the version to 0.1.0
      - name: Promote package version to release
        run: |
          poetry version patch

      - name: Build Python package
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          poetry build

      - name: Publish the package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ github.event.release.target_commitish == 'main' }}
        with:
          packages-dir: dist/

      - name: Bump poetry version to next alpha version
        run: |
          poetry version prepatch

      - name: Commit files
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --tags -f
          git commit -m "Bump package version" -a

      - name: Push changes
        if: ${{ github.event.release.target_commitish == 'main' }}
        run: |
          git push
